# https://taskfile.dev

version: "3"

env:
  PYTHON_SRC: prezmanifest
  TESTS_DIR: tests

tasks:
  install:
    cmds:
      - uv sync

  format:
    desc: Format Python code.
    cmds:
      - uv run ruff format $PYTHON_SRC
      - uv run ruff check --select I --fix $PYTHON_SRC
      - uv run ruff format $TESTS_DIR
      - uv run ruff check --select I --fix $TESTS_DIR

  require-docker:
    desc: "Ensure Docker Desktop is running"
    preconditions:
      - sh: docker info >/dev/null 2>&1
        msg: |
          ❌ Docker Desktop is not running.
          Please start Docker Desktop and try again.

  test:
    desc: Run tests
    deps:
      - require-docker
    cmds:
      - uv run pytest $TESTS_DIR -rP

  fusekiup:
    cmd: docker compose up -d

  fusekidown:
    cmd: docker compose down
